# Fungsi Program Concatenate Score
<ul>
  <li>Kasus perlu prgram ini: Mengajar di salah satu matakuliah, tetapi matakuliah tersebut ada dua kelas berbeda. Misalnya, mengajar matakuliah A di Kelas Pagi dan Kelas Malam</li>
  <li>Jalankan <i>program_get_score.ipynb</i> terlebih dahulu untuk mendapatkan nilai kedua kelas tersebut </li>
  <li>Output dari kedua <i>program_get_score.ipynb</i> tersebut akan menjadi input program <i>concatenate_score.ipynb</i></li>
</ul>

# 1. Buka File di Direktori
Defenisikan lokasi data dua output dari <i>program_get_score.ipynb</i> yang ingin digabungkan

In [45]:
import pandas as pd
import numpy as np

# Database Nilai Pertama
data1 =  pd.read_excel('output1.xlsx')
data1.drop(data1.columns[0], axis=1, inplace=True)

# Database Nilai Kedua
data2 = pd.read_excel('output2.xlsx')
data2.drop(data2.columns[0], axis=1, inplace=True)

In [46]:
data1

,No,NIM,Nama,Email,Absensi Pertemuan 1,Absensi Pertemuan 2,Absensi Pertemuan 3,Absensi Pertemuan 4,Absensi Pertemuan 5,Absensi Pertemuan 6,Absensi Pertemuan 8,Absensi Pertemuan 9,Tugas Mandiri 1,Tugas Mandiri 2,Tugas Mandiri 3,Ujian Tengah Semester (UTS)
0,1,20040046,HILDA ANGGIE JULIANA MANGUNSONG,anggiesimangungsong@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,20040047,AULIA RACHMAH NUR,auliarachmahnur21@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,20040048,MEGA LIDIA LUBIS,megalubis9@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,20040049,CICI LAURENA SIHOTANG,cicilaurena@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,20040051,WULANDARI,wulandariii550@gmail.com,100.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,135,20040230,ALFI SYAHRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,136,20040231,ORIS NELLY SIANIPAR,orisnellyspr@gmail.com,100.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
139,137,20040232,CHANI LYA ERVINATA SIANIPAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,138,20040233,PANJI SINAGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,139,20040244,DORMIAN SIGIRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
data2

,No,NIM,Nama,Email,Absensi Pertemuan 1,Absensi Pertemuan 2,Absensi Pertemuan 3,Absensi Pertemuan 4,Absensi Pertemuan 5,Absensi Pertemuan 6,Absensi Pertemuan 8,Absensi Pertemuan 9,Tugas Mandiri 1,Tugas Mandiri 2,Tugas Mandiri 3,Ujian Tengah Semester (UTS)
0,1,20040046,HILDA ANGGIE JULIANA MANGUNSONG,anggiesimangungsong@gmail.com,0.0,0.0,0.0,100.0,100.0,100.0,100.0,NaN,90.0,80.0,NaN,70.0
1,2,20040047,AULIA RACHMAH NUR,auliarachmahnur21@gmail.com,100.0,100.0,100.0,0.0,100.0,100.0,100.0,NaN,70.0,65.0,NaN,95.0
2,3,20040048,MEGA LIDIA LUBIS,megalubis9@gmail.com,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,100.0,100.0,NaN,100.0
3,4,20040049,CICI LAURENA SIHOTANG,cicilaurena@gmail.com,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,20.0,65.0,NaN,95.0
4,5,20040051,WULANDARI,wulandariii550@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,135,20040230,ALFI SYAHRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,136,20040231,ORIS NELLY SIANIPAR,orisnellyspr@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,137,20040232,CHANI LYA ERVINATA SIANIPAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,138,20040233,PANJI SINAGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,139,20040244,DORMIAN SIGIRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Membersihkan data

In [48]:
# mendapatkan daftar header
dataset_head = list(data1.columns)

In [49]:
gabung = data1.combine_first(data2)

In [50]:
gabung = gabung.reindex(sorted(gabung.columns), axis=1)

first_cols = dataset_head[:4]
last_cols = [col for col in gabung.columns if col not in first_cols]

gabung = gabung[first_cols+last_cols]

In [51]:
gabung

,No,NIM,Nama,Email,Absensi Pertemuan 1,Absensi Pertemuan 2,Absensi Pertemuan 3,Absensi Pertemuan 4,Absensi Pertemuan 5,Absensi Pertemuan 6,Absensi Pertemuan 8,Absensi Pertemuan 9,Tugas Mandiri 1,Tugas Mandiri 2,Tugas Mandiri 3,Ujian Tengah Semester (UTS)
0,1,20040046,HILDA ANGGIE JULIANA MANGUNSONG,anggiesimangungsong@gmail.com,0.0,0.0,0.0,100.0,100.0,100.0,100.0,NaN,90.0,80.0,NaN,70.0
1,2,20040047,AULIA RACHMAH NUR,auliarachmahnur21@gmail.com,100.0,100.0,100.0,0.0,100.0,100.0,100.0,NaN,70.0,65.0,NaN,95.0
2,3,20040048,MEGA LIDIA LUBIS,megalubis9@gmail.com,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,100.0,100.0,NaN,100.0
3,4,20040049,CICI LAURENA SIHOTANG,cicilaurena@gmail.com,100.0,100.0,100.0,100.0,100.0,100.0,100.0,NaN,20.0,65.0,NaN,95.0
4,5,20040051,WULANDARI,wulandariii550@gmail.com,100.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,135,20040230,ALFI SYAHRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,136,20040231,ORIS NELLY SIANIPAR,orisnellyspr@gmail.com,100.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0
139,137,20040232,CHANI LYA ERVINATA SIANIPAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,138,20040233,PANJI SINAGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,139,20040244,DORMIAN SIGIRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
gabung.to_excel("output_gabung.xlsx")

# writer = pd.ExcelWriter('output.xlsx',
#                         engine='xlsxwriter',
#                         options={'strings_to_numbers': True})